### ISSUE TITLE
Support "include(fix_file)" fix command

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu#101]
It's now possible to include fixes from a file using catmandu.yml:

 fixer:
    default:
        - myfixes.txt

but one cannot refer to a file from "myfixes.txt".

Should come in handy to organise your fixes

**Comment by nichtich** [comment]
Where is it documented and implemented in which release, so we can close this issue?

**Comment by nicolasfranck** [comment]
See perldoc for Catmandu::Fix : 

```
my $fixer = Catmandu::Fix->new(fixes => ['fix_file.txt']);
```
In Catmandu::Fix the method _build_fixes loads the commands from the referenced
file, and adds them to the list of fixes:

```
sub _build_fixes {
  ..
        } elsif (is_string($fix)) {
            push @$fixes, @{$self->parser->parse($fix)};
        }
  ..
}
```

**Comment by vpeil** [comment]
I'm confused. What do we talk about? The title says `fix files in fix files`, the example is about `fix files in config files`.  The first is nice to have, the last one works for me....

**Comment by phochste** [comment]
There is a confuction. There isn't anything implemented ,  documented or added by Nicolas. This is a new feature request. I've updated the title of this ticket to clarify

**Comment by vpeil** [comment]
yes, that would be a great fix to organize your fix files!

**Comment by nicolasfranck** [comment]
look for brach "include":

https://github.com/LibreCat/Catmandu/blob/include/lib/Catmandu/Fix/include.pm

has to be merged into dev branch.
