### ISSUE TITLE
Better document Installation

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#108]
The link to installation wiki at https://metacpan.org/pod/Catmandu#ONE-STEP-INSTALL is broken and it refers to Task::Catmandu instead of core Catmandu. Better document Installation of Core Catmandu at different platforms.

**Comment by vpeil** [comment]
see cf5a17f566c6d0ecc96f62e67de3e53fe6c89619

**Comment by nics** [comment]
remove the references to Task::Catmandu?

**Comment by vpeil** [comment]
then we should clean up the whole documentation and remove Task::Catmandu everywhere, e.g. https://github.com/LibreCat/Catmandu/wiki/Installation

**Comment by nics** [comment]
yes and remove it from cpan

**Comment by nics** [comment]
removed references to the Task in f3c296b9c29ed2b3023d0d6e756347f0f09d17af
