### ISSUE TITLE
bag and store miss a drop method

### ISSUE THREAD

**Issue by nics** [LibreCat/Catmandu#11]

**Comment by vpeil** [comment]
has been implemented in the stores Elasticssearch and MongoDB long ago.

**Comment by nics** [comment]
The other stores should have it too and Bag.pm should require the method.

**Comment by nics** [comment]
We should think about the behavior after calling drop.
    $bag->drop
    $bag->add({})
Does this recreate the bag or die? I would choose to recreate since calling add on a nonexisting bag also autocreates.

**Comment by nics** [comment]
Merged in 538428acd1147f6f8d5630d6133d9ecd02f051a0.
Stores have drop (drop store and all bags) and drop_bags (drop all bags) methods
Bags have a drop method.
Stores outside of core Catmandu will need to be updated before 1.0.
