### ISSUE TITLE
Catmandu::Fix::cmd should be optional

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu#111]
Due to the fact that one of my fix files where "executable" (yes, I know),
Catmandu loads them as executable files using Catmandu::Fix::cmd.

A handy feature, but  this should be made explicit in the configuration,
in order to avoid this unwanted behaviour.

**Comment by nichtich** [comment]
Removing support of executables as `--fix` breaks backwards compatibility but sounds reasonable. We could then add support via dedicated options such as:

    --check ./mycommand # must return true exit code
    --pipe ./mycommand # as explained above (with 1-to-n mapping)

**Comment by nics** [comment]
pod references also removed in 039a9a087fb849f1b842b3bd7fb561c7859519d9
