### ISSUE TITLE
pluck(my.deep.field) fix command

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#117]
Writing documentation for easy examples how to use Catmandu I see that we have a very verbose way to read only one field out of a JSON. It requires always a combination of multiple retain_fields or a retain_field,remove_field combination or more.

I would like to see a 

```
pluck(my.deep.field)
```

Which results in keeping only my.deep.field and nothing more or less.

**Comment by nichtich** [comment]
The difference between `retain_field(my.deep.field)` and `pluck(my.deep.field)` should be made clear. I'd prefer `retain_only` instead of `retain`.

**Comment by phochste** [comment]
Available as ```retain```
