### ISSUE TITLE
Error handling broken in catmandu 0.9209

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#123]
Throwing of Catmandu::ParseError  is broken in version 0.9209

Test:

    package Catmandu::Fix::error;
    use Moo;

    package main;
    use Catmandu;
    use Catmandu::Fix;
    use Try::Tiny;

    try {
      my $fixer = Catmandu::Fix->new(fixes => ['error()']);
      $fixer->fix({});
    }
    catch  {
       printf "1: throws: %s\n" , ref($_);
    };

    try {
      my $fixer = Catmandu::Fix->new(fixes => ['brol((((((((']);
      $fixer->fix({});
    }
    catch  {
       printf "2: throws: %s\n" , ref($_);
    };

Should produce:

    1: throws: Catmandu::FixError
    2: throws: Catmandu::ParseError

But gives

    1: throws: Catmandu::FixError
    2: throws:

**Comment by nics** [comment]
fixed in 999fbe09dee9528e2673f3e77923a661795e687a
