### ISSUE TITLE
Catmandu::Transactionable for Catmandu::Store?

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu#126]
The Catmandu::Store::DBI has the method "transaction" for quite a time.
This enables you to add/delete records, and rollback the changes when something
happens.

But Solr also supports this behaviour. Shouldn't we add the interface Catmandu::Transactionable
for this behaviour? Both DBI and Solr can inherit from it.

I'll make a branch for it in Catmandu and Catmandu-Solr, called catmandu-transactionable

**Comment by nics** [comment]
added in a0739250690ee71f80bb7b6c54a6c219c3ed922b
