### ISSUE TITLE
Catmandu::Iterable next()

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#131]
I have some need to build some algorithms that require a next() method on an iterator. Basically a sort of alias for the generator of the Iterator.

Situation:

     my $it   = Catmandu->importer();
     my $obj = $it->next();
    
     (do a lot of stuff .. callbacks etc ...)

      $obj = $it->next();

**Comment by nics** [comment]
implemented in afa434d96e92df4eddfb7c4e39f536acfe782597
