### ISSUE TITLE
Make sure all items have all fields

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#132]
CSV exporter (and Catmandu::Exporter::Table) only export fields given explicitly by configuration or taken from the first item. This is a problem if the set of fields is not known from the start. There should be an option to first collect all items. I am not sure whether this could also be a general option for iterators:

```
my $all = $importer->to_array;
my %fields;
for my $item (@$all) {
    $fields{$_} ||= 1 for keys %$item;
}   
for my $item (@$all) {
    $item->{$_} //= '' for %$fields;
}
```

**Comment by nics** [comment]
a new TabularExporter role provides this functionality through the collect_fields option. See the pod for more info. Right now only the CSV exporter is consuming this role. Exporters for other tabular formats could also take advantage of it's extra functionality.

**Comment by nichtich** [comment]
Thanks, I'll have a look at other tabular exporters :-)

On 17. Dezember 2015 15:53:00 MEZ, Nicolas Steenlant <notifications@github.com> wrote:
>a new TabularExporter role provides this functionality through the
>collect_fields option. See the pod for more info. Right now only the
>CSV exporter is consuming this role. Exporters for other tabular
>formats could also take advantage of it's extra functionality. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LibreCat/Catmandu/issues/132#issuecomment-165474197

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
