### ISSUE TITLE
Catmandu::Importer::RIS

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#134]
Is missing as counterpart of Catmandu::Exporter::RIS (but with custom fields).

**Comment by vpeil** [comment]
@nichtich please have a look at commit 719fcbb295da6. works for you?

**Comment by vpeil** [comment]
as suggested by @nics, the RIS stuff has been moved to its own distro: https://github.com/LibreCat/Catmandu-RIS,
