### ISSUE TITLE
Replace README.md with more end-user friendly version

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#149]
The current README.md aims at developers, it should better describe simple installation, basic usage and refer to additional documentation.

**Comment by phochste** [comment]
The README.md is automatically generated from the lib/Catmandu.pm when using Dist::Milla. I don't want to throw away the documentation for Catmandu.pm which is needed for developers. 

Does anyone know how to point Dist::Milla to another POD file for README.md generation?

**Comment by vpeil** [comment]
Have a look at this one: https://metacpan.org/pod/Dist::Zilla::Plugin::ReadmeAnyFromPod

It should be possible to override Dist::Milla's default behaviour.

**Comment by phochste** [comment]
Super :)
