### ISSUE TITLE
add alias `name` , e.g. for `index_name`

### ISSUE THREAD

**Issue by vpeil** [LibreCat/Catmandu#151]
for elasticsearch it is

``` terminal
$ catmandu import to ElasticSearch --index_name test --bag test <file.json
```

for mongodb it is

``` terminal
$ catmandu import to MongoDB --database_name test --bag test <file.json
```

and for anther store whatever. Better is to use `name` and map it correctly in the background...

The same should be done, when using directly in Perl code.

**Comment by nichtich** [comment]
Which module do you refer to? Could you create an overview?

**Comment by nichtich** [comment]
@vpeil can this be closed? My impression of current stores is they are too different for a unified naming scheme.

**Comment by vpeil** [comment]
indeed.  thanks for reminding.
