### ISSUE TITLE
Update documentation of fix package creation

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#154]
Creation of fix packages is poorly documented or documentation is outdated. When to use `fix_arg`, and `fix_opt` and when to use `BUILDARGS`? Documentation should be findable here:

* [Catmandu::Fix](https://metacpan.org/pod/Catmandu::Fix)
* [Catmandu::Fixable](https://metacpan.org/pod/Catmandu::Fixable)
* http://librecat.org/Catmandu/#fix-packages

I am not sure how the blog articles http://librecat.org/catmandu/2014/03/14/create-a-fixer.html and http://librecat.org/catmandu/2014/03/26/creating-a-fixer-2.html are still up to date.

**Comment by phochste** [comment]
The blog posts are still up to date. They work, but there are now more helper packages available that ease (a bit) the creation of emit Fixes.
