### ISSUE TITLE
Merge all field in a HASH or ARRAY with the root node

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#156]
Given the data:

     ----
    foo:
       alpha: bla
       bravo: bla
       charly: bla
       delta: bla
       .
       .
       yankee: bla
       zulu:

I would like to move all the fields in foo to the root with one fix:

     move_field(foo.*,'')

**Comment by nichtich** [comment]
How about

    move_field(foo.*,'.')

instead so a path starting with a dot starts with the root and a single dot refers to the root?

**Comment by nics** [comment]
the issue here is not referring to the root but matching hash keys with wildcards. current semantics for move_field(foo.*, .) would be something like 'set every match for foo.* in turn as root'. What you need is something like 'move_field(foo.*, .*) that works for hashes (and arrays too)'

**Comment by vpeil** [comment]
This one already works:
```
move_field( foo, . )
```
so, nothing to do here!?
