### ISSUE TITLE
incorrect VERSION sub

### ISSUE THREAD

**Issue by karenetheridge** [LibreCat/Catmandu#163]
```
sub VERSION {
    $Catmandu::VERSION;
}
```

This is wrong. See perldoc UNIVERSAL. A VERSION sub should check the arguments that are passed in. This sub can just be removed, to make it behave properly.

**Comment by nics** [comment]
Thanks for the heads up. Fixed in 9809efbb8221d83b206e3b4b0ce9aca127c8505d.
