### ISSUE TITLE
Better document Catmandu::Paged

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#164]
The documentation of [Catmandu::Paged](https://metacpan.org/pod/Catmandu::Paged) only list methods in SYNOPSIS without explanation. Are paged counted from 0 or from 1? What does `next` return compared to `next_page`? What does `page_size` return compared to `limit`? What is `page_ranges` and `pages_in_spread`? The module should also be referenced more explicitly in [Catmandu::Hits](https://metacpan.org/pod/Catmandu::Hits).

**Comment by phochste** [comment]
I have no idea what 'page_ranges' and 'pages_in_spread' do. The 'page_ranges' throws an undef error in the example given. 

@vpeil can you give some hints?

**Comment by vpeil** [comment]
Glad to have tests! Have a look at
https://github.com/LibreCat/Catmandu/blob/dev/t/Catmandu-Paged.t#L85

`pages_in_pread` gives gives the previous pages und next pages, depending on you current position, this is very handy for pagination calc in templates.

Unfortunately I'm not sure, what  `page_ranges` is for  (and test is missing for this method :disappointed: )
