### ISSUE TITLE
Build failing on Ubuntu 12.04

### ISSUE THREAD

**Issue by minorscience** [LibreCat/Catmandu#172]
I'm a reasonably experienced sysadmin and have been trying unsuccessfully to get this tool built since April. I don't have a lot of perl experience (use mostly ruby) so I may be missing something obvious.

Built a bare bones Ubuntu box with veewee and deployed with Vagrant. Installation bails out as follows:

! Installing the dependencies failed: Module 'Catmandu::XML' is not installed
! Bailing out the installation for Task-Catmandu-0.104.

As I recall, there was an undocumented dependency. I've attempted to downgrade to XML-Struct-0.23 with no luck. Output below. Any ideas?

<pre>
root@catmandu:/home/vagrant/XML-Struct-0.23# /usr/local/bin/cpanm Task::Catmandu --force
--> Working on Task::Catmandu
Fetching http://www.cpan.org/authors/id/N/NI/NICS/Task-Catmandu-0.104.tar.gz ... OK
Configuring Task-Catmandu-0.104 ... OK
==> Found dependencies: Catmandu::XML
--> Working on Catmandu::XML
Fetching http://www.cpan.org/authors/id/V/VO/VOJ/Catmandu-XML-0.16.tar.gz ... OK
Configuring Catmandu-XML-0.16 ... OK
==> Found dependencies: XML::LibXSLT
--> Working on XML::LibXSLT
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-1.94.tar.gz ... OK
Configuring XML-LibXSLT-1.94 ... OK
Building and testing XML-LibXSLT-1.94 ... FAIL
! Installing XML::LibXSLT failed. See /root/.cpanm/work/1438198830.30480/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'XML::LibXSLT' is not installed
! Bailing out the installation for Catmandu-XML-0.16.
! Installing the dependencies failed: Module 'Catmandu::XML' is not installed
! Bailing out the installation for Task-Catmandu-0.104.
</pre>

**Comment by minorscience** [comment]
Entire log file posted here. Looks like an issue with ld. Pretty low-level problem, so not sure where to go with this. 

/usr/bin/ld: cannot find -lgdbm
/usr/bin/ld: cannot find -lgdbm_compat

<pre>
cpanm (App::cpanminus) 1.7039 on perl 5.014002 built for x86_64-linux-gnu-thread-multi
Work directory is /root/.cpanm/work/1438198830.30480
You have make /usr/bin/make
You have LWP 6.03
You have /bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Searching Task::Catmandu () on cpanmetadb ...
--> Working on Task::Catmandu
Fetching http://www.cpan.org/authors/id/N/NI/NICS/Task-Catmandu-0.104.tar.gz
-> OK
Unpacking Task-Catmandu-0.104.tar.gz
Entering Task-Catmandu-0.104
Checking configure dependencies from META.json
Checking if you have Module::Build::Tiny 0.039 ... Yes (0.039)
Configuring Task-Catmandu-0.104
Running Build.PL
Creating new 'Build' script for 'Task-Catmandu' version '0.104'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Catmandu::BibTeX 0.06 ... Yes (0.06)
Checking if you have Catmandu::Validator::JSONSchema 0.1 ... Yes (0.1)
Checking if you have Catmandu::Exporter::Table v0.2.1 ... Yes (0.3.0)
Checking if you have Catmandu::Fix::cmd 0.0201 ... Yes (0.0201)
Checking if you have Catmandu::Fix::Date 0.0121 ... Yes (0.0123)
Checking if you have Catmandu::MAB2 0.07 ... Yes (0.07)
Checking if you have Catmandu::XLS 0.04 ... Yes (0.05)
Checking if you have Catmandu 0.9206 ... Yes (0.94)
Checking if you have Catmandu::MODS 0.2 ... Yes (0.3)
Checking if you have Catmandu::XML 0.14 ... No
Checking if you have Catmandu::Store::CHI 0.02 ... Yes (0.02)
Checking if you have Catmandu::Serializer::storable 0.0102 ... Yes (0.0102)
Checking if you have Catmandu::RDF 0.18 ... Yes (0.27)
Checking if you have Catmandu::MARC 0.205 ... Yes (0.210)
Checking if you have Catmandu::Wikidata 0.06 ... Yes (0.06)
Checking if you have Catmandu::OAI 0.06 ... Yes (0.08)
Checking if you have Catmandu::Exporter::Template 0.05 ... Yes (0.08)
Checking if you have Catmandu::Cmd::repl 0.01 ... Yes (0.01)
Checking if you have Catmandu::Atom 0.02 ... Yes (0.04)
Checking if you have Catmandu::PICA 0.15 ... Yes (0.15)
Checking if you have Catmandu::Fix::get_json 0.40 ... Yes (0.50)
Checking if you have Catmandu::LDAP 0.0103 ... Yes (0.0103)
Checking if you have Catmandu::Importer::Twitter 0.03 ... Yes (0.03)
Checking if you have Catmandu::SRU 0.037 ... Yes (0.038)
==> Found dependencies: Catmandu::XML
Searching Catmandu::XML (0.14) on cpanmetadb ...
--> Working on Catmandu::XML
Fetching http://www.cpan.org/authors/id/V/VO/VOJ/Catmandu-XML-0.16.tar.gz
-> OK
Unpacking Catmandu-XML-0.16.tar.gz
Entering Catmandu-XML-0.16
Checking configure dependencies from META.json
Checking if you have Module::Build::Tiny 0.039 ... Yes (0.039)
Configuring Catmandu-XML-0.16
Running Build.PL
Creating new 'Build' script for 'Catmandu-XML' version '0.16'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have XML::LibXSLT 1.78 ... No
Checking if you have XML::Struct 0.26 ... Yes (0.26)
Checking if you have Catmandu 0.9 ... Yes (0.94)
==> Found dependencies: XML::LibXSLT
Searching XML::LibXSLT (1.78) on cpanmetadb ...
--> Working on XML::LibXSLT
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-1.94.tar.gz
-> OK
Unpacking XML-LibXSLT-1.94.tar.gz
Entering XML-LibXSLT-1.94
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.04)
Configuring XML-LibXSLT-1.94
Running Makefile.PL
running xslt-config... ok
looking for -lxslt... yes
looking for -lexslt... yes
running pkg-config libexslt... using fallback values for LIBS and INC
failed
Checking if your kit is complete...
Looks good
Warning (mostly harmless): No library found for -ldb
Generating a Unix-style Makefile
Writing Makefile for XML::LibXSLT
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have strict 0 ... Yes (1.04)
Checking if you have warnings 0 ... Yes (1.12)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04)
Checking if you have XML::LibXML 1.70 ... Yes (2.0121)
Checking if you have Encode 0 ... Yes (2.75)
Building and testing XML-LibXSLT-1.94
cp LibXSLT.pm blib/lib/XML/LibXSLT.pm
Running Mkbootstrap for XML::LibXSLT ()
chmod 644 "LibXSLT.bs"
"/usr/bin/perl" "/usr/local/share/perl/5.14.2/ExtUtils/xsubpp"  -typemap "/usr/share/perl/5.14/ExtUtils/typemap" -typemap "typemap"  LibXSLT.xs > LibXSLT.xsc && mv LibXSLT.xsc LibXSLT.c
cc -c  -I/usr/include/libxml2  -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.94\" -DXS_VERSION=\"1.94\" -fPIC "-I/usr/lib/perl/5.14/CORE"  -DHAVE_BLANK -DHAVE_BLANK -DHAVE_EXSLT LibXSLT.c
cc -c  -I/usr/include/libxml2  -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.94\" -DXS_VERSION=\"1.94\" -fPIC "-I/usr/lib/perl/5.14/CORE"  -DHAVE_BLANK -DHAVE_BLANK -DHAVE_EXSLT perl-libxml-mm.c
rm -f blib/arch/auto/XML/LibXSLT/LibXSLT.so
LD_RUN_PATH="/usr/lib/x86_64-linux-gnu" cc  -shared -O2 -g -L/usr/local/lib -fstack-protector LibXSLT.o perl-libxml-mm.o  -o blib/arch/auto/XML/LibXSLT/LibXSLT.so 	\
	   -L/usr/lib/x86_64-linux-gnu -lxslt -lxml2 -lz -lm -lexslt -lgdbm -lgdbm_compat -ldl -lm -lpthread -lc -lcrypt  	\
	  
/usr/bin/ld: cannot find -lgdbm
/usr/bin/ld: cannot find -lgdbm_compat
collect2: ld returned 1 exit status
make: *** [blib/arch/auto/XML/LibXSLT/LibXSLT.so] Error 1
-> FAIL Installing XML::LibXSLT failed. See /root/.cpanm/work/1438198830.30480/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'XML::LibXSLT' is not installed
-> FAIL Bailing out the installation for Catmandu-XML-0.16.
-> FAIL Installing the dependencies failed: Module 'Catmandu::XML' is not installed
-> FAIL Bailing out the installation for Task-Catmandu-0.104.
</pre>

**Comment by minorscience** [comment]
Tried again with a fresh box. Many unmet undependencies. Followed instructions for Ubuntu 12.04 LTS on the installation page to the letter. PM me for complete build.log, too long to post here.

**Comment by minorscience** [comment]
Attempting to install on CentOS 6.4 now and encountering further issues, i.e. 

<pre>
Result: FAIL
Failed 45/45 test programs. 0/0 subtests failed.
make: *** [test_dynamic] Error 2
  INGY/YAML-1.15.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports INGY/YAML-1.15.tar.gz
Warning (usually harmless): 'YAML' not installed, will not store persistent state
Running make install
  make test had returned bad status, won't install without force
</pre>

**Comment by pietsch** [comment]
The cpanm tool cannot install all the required dependencies automatically, only those that are CPAN packages. Some system libraries need to be installed first. Please take a loot at http://librecat.org/Catmandu/#installation

**Comment by pkiraly** [comment]
I was able to follow installation after installing libgdbm-dev with `sudo apt-get install libgdbm-dev` (in Ubuntu 14.04)

**Comment by phochste** [comment]
Added the libgdbm-dev hint to the installation instructions on the wiki
