### ISSUE TITLE
Support delimited key-value pairs format

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#174]
The [miller command line tool for data processing](http://johnkerl.org/miller/doc/file-formats.html) uses "delimited key-value pairs":

```
a=pan,b=pan,i=1,x=0.3467901443380824,y=0.7268028627434533
a=eks,b=pan,i=2,x=0.7586799647899636,y=0.5221511083334797
a=wye,b=wye,i=3,x=0.20460330576630303,y=0.33831852551664776
```

Escaping is not supported but the format is enough for many cases. Field delimiter (here: comma) could be configurable.

**Comment by nichtich** [comment]
Can almost be done with this importer:

~~~.yaml
---
importer:
  kvpairs:
    package: Text
    options:
      split: ","
      fix:
        - "parse_text(text.*,'(.?+)=(.*)')"
        - "hash(text.*)"
~~~

The fix is incomplete, it requires merging hashes in field `text` and moving them to the root. The current output of first line is:

~~~.json
{"_id":1,"text":[{"a":"pan"},{"b":"pan"},{"i":"1"},{"x":"0.3467901443380824"},{"y":"0.7268028627434533"}]}
~~~

Any ideas how to proceed?

**Comment by nics** [comment]
A new hash_merge fix? Hash::Merge::Simple is already a dependency. Seems quite useful.

**Comment by nichtich** [comment]
Do we have array_merge and wouldn't be a general merge more convenient?

On 26. April 2016 16:31:04 MESZ, Nicolas Steenlant <notifications@github.com> wrote:
>A new hash_merge fix? Hash::Merge::Simple is already a dependency.
>Seems quite useful.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LibreCat/Catmandu/issues/174#issuecomment-214764421

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by nics** [comment]
05141e6c47156f57d9603fdded8ebbb96470f7d2 adds a new DKVP importer.
