### ISSUE TITLE
JSON and YAML exporters turn rejected records into null values

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#177]
If I have a data file test.json:

    {"ok":"1"}
    {"ok":"1"}
    {"ok":"1"}

and do in the development branch:

    carton exec 'perl -I lib bin/catmandu convert JSON to JSON --fix "reject()" < test.json'

then I get as answer:

    null
    null
    null

With the YAML exporter I get:

    --- ~
    ...
    --- ~
    ...
    --- ~
    ...

The CSV export is ok: an empty response is returned.

**Comment by nics** [comment]
fixed in  da22c75dd150fdc655c2852e39bb451a48f8e46f
