### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by slobo** [LibreCat/Catmandu#187]
Perhaps I missed existing functionality, but it would be great if we could have a progress meter for operations. Even something as simple as total number of items processed. I suppose one could use a Fixer for this, but seems kind of dirty, no?

For stuff like DBI, we could even request a `COUNT(*)` and use that to show percentage progress/eta, etc.

**Comment by phochste** [comment]
There is a progress meter for operations. E.g. for the command line tool there is the -v option:


catmandu convert -v IMPORTER to EXPORTER < data

catmandu import   -v IMPORTER to STORE

catmandu export   -v STORE to EXPORTER


In the Perl API itself there is the benchmark() method you can attach to any Catmandu::Iterable. E.g.


use Catmandu;


my $importer = Catmandu->importer(JSON, file => 'data.json');


$importer->benchmark()->each(sub {

    my $item = shift;

    # your code

});


Cheers

Patrick


________________________________

**Comment by slobo** [comment]
Ah, thats the stuff - works great, thanks!
