### ISSUE TITLE
first try: OAI not installed by default in the docker image

### ISSUE THREAD

**Issue by kerphi** [LibreCat/Catmandu#191]
I just quickly tried this script (thanks to the docker image) and I tried to run few example but I'm blocked on this first one:

```bash
root@24f7952cf48c:/home# catmandu convert OAI --url http://biblio.ugent.be/oai --set allFtxt to JSON
Oops! Can't find the importer 'OAI' in your configuration file or Catmandu::Importer::OAI is not installed.
```

I quickly search in the doc to install  Catmandu::Importer::OAI but I failed to find how. I belive it's somewhere into the CPAN world, but I do not know a lot about perl and cpan... 
Maybe it would be goot to have all the basic modules installed by default in the docker image ?

**Comment by jorol** [comment]
You can install additional Perl modules via:

```terminal
$ cpanm Catmandu::OAI
```

**Comment by nics** [comment]
Hello Stéphane,

running

	cpanm Catmandu::OAI

will install the OAI component.

However, due to an SSL certificate problem your specific example still fails, other OAI providers work fine however:

	catmandu convert OAI --url http://europepmc.org/oai.cgi to JSON

Regards,
Nicolas

**Comment by kerphi** [comment]
Thank you for the quick answers.

I successfullyinstalled the module.

But the oai pmh examples do not work, probably because of our internal
proxy.

Here is the error :
root@59d2719fe87d:/home# catmandu convert OAI --url
http://europepmc.org/oai.cgi to JSON
resumptionToken() : Can't connect to europepmc.org:80 at
/usr/local/share/perl/5.20.2/Catmandu/Addable.pm line 125.

Here is our proxy i just configured in the environment variables:
root@59d2719fe87d:/home# env | grep http
http_proxy=http://proxyout.inist.fr:8080
https_proxy=http://proxyout.inist.fr:8080



On Wed, Oct 14, 2015 at 9:12 AM, Nicolas Steenlant <notifications@github.com

**Comment by jorol** [comment]
The new version v.0.11 of Catmandu::OAI supports proxys.

```terminal
$ cpanm Catmandu::OAI
$ catmandu convert OAI --url http://europepmc.org/oai.cgi to JSON
{"creator":["Sharp, D. G.","Eckert, Edward A.","Beard, Dorothy","Beard, J. W."],"language":["en"],"_about":[],"_id":"oai
:europepmc.org:108","title":["MORPHOLOGY OF THE VIRUS OF AVIAN ERYTHRO-MYELOBLASTIC LEUCOSIS AND A COMPARISON WITH THE A
GENT OF NEWCASTLE DISEASE1"],"_status":"","rights":["Copyright, 1952, The Williams & Wilkins Company"],"_identifier":"oa
i:europepmc.org:108","identifier":["http://europepmc.org/articles/PMC169245","http://europepmc.org/abstract/MED/14938295
"],"_datestamp":"2010-09-08","subject":["Articles"],"type":["Text"],"_setSpec":["jbacter"],"date":["1952-02"],"descripti
on":[""]}
{"_status":"","rights":["Copyright, 1952, The Williams & Wilkins Company"],"identifier":["http://europepmc.org/articles/
PMC169246","http://europepmc.org/abstract/MED/14938296"],"_datestamp":"2010-09-08","_identifier":"oai:europepmc.org:109"
,"subject":["Articles"],"description":[""],"date":["1952-02"],"type":["Text"],"_setSpec":["jbacter"],"creator":["Whitele
y, H. R."],"language":["en"],"_about":[],"title":["THE FERMENTATION OF PURINES BY MICROCOCCUS AEROGENES"],"_id":"oai:eur
opepmc.org:109"}
...
```

**Comment by kerphi** [comment]
Great ! it works
