### ISSUE TITLE
Catmandu::Fix::expand has limited array size of 100

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/Catmandu#196]
This fix uses CGI::Expand, which limits the size of any array to 100 values ($CGI::Expand::Max_Array)

Can we make this configurable?

**Comment by nics** [comment]
fixed in dev (commits 43689e48e1e7679aaad8ce2cbf129d7fe926f58c and 3aa08ff2d9b1236ff0ddc39a635e0e5a38f0e949)
