### ISSUE TITLE
consider use MooX::Role::Logger

### ISSUE THREAD

**Issue by jonassmedegaard** [LibreCat/Catmandu#199]
Hi,

I recommend to consider replacing Catmandu::Logger with the generic MooX::Role::Logger.  To me that seems the better replacement for MooX::Log::Any.
  
Also, you might consider splitting out the parts of Catmandu that uses Log::Any::Adapter into an App::Catmandu distribution only recommended by the core Catmandu distribution - to invite reuse of Catmandu framework with different frontends and logging mechanisms than the ones you've implemented.  I.e. to play along with the logic of Log::Any. :-)

**Comment by nics** [comment]
Catmandu uses MooX::Role::Logger with commit 5a201ee529a76abcd6273c41bd54fc89f1f7384f. Something like App::Catmandu would indeed by cleaner. But Catmandu only loads and sets the adapter if you use Catmandu::CLI or run the tests. If you use Catmandu as a library it is logger agnostic.
