### ISSUE TITLE
improve error handling in addable

### ISSUE THREAD

**Issue by nics** [LibreCat/Catmandu#202]
when adding and then commiting many items, error information can get lost. There should at least be an an error handler.

**Comment by nichtich** [comment]
Errors should be reported to `Catmandu->log`, don't they?

**Comment by nics** [comment]
That would be a good default. But i would like the behavior to be overridable.

**Comment by nics** [comment]
actually, this is only a problem for stores that batch add and fixing this can only be done at their level, so i'm closing this ticket
