### ISSUE TITLE
Installation on OSX w/ Perlbrew

### ISSUE THREAD

**Issue by netsensei** [LibreCat/Catmandu#205]
Hi,

Since I'm working with Mac/OSX, I referred to the installation instructions on the about page:

http://librecat.org/Catmandu/#windows-mac-osx-linux

They mention either running Docker or installing ActivePerl:

(1) Long story short: Docker runs in a dedicated VM on OSX. So, you need to basically ssh into the VM before you can use catmandu. Great to try things out or one offs, not so great for day-to-day operations.
(2) Native via ActivePerl: Yes. But I wondered if I could avoid installing Perl via a vendor specific, binary package.

Enter:  http://perlbrew.pl/

Works a bit like RVM (Ruby) https://rvm.io/ or NVM (NodeJS) https://github.com/creationix/nvm Allows you to install one or multiple self-contained Perl base installations and easily switch between versions. OSX comes with a system Perl installation which you generally don't want to mess with.

So, I successfully installed Catmandu natively on OSX with perlbrew.  Small gist:

```bash
curl -L http://install.perlbrew.pl | bash # installs perlbrew
perlbrew install perl-5.22.0  # installs a fresh, isolated perl base in your home folder
perlbrew switch perl-5.22.0 # use perl 5.22.0 binary instead of 5.18.0
perlbrew install-cpanm # install cpanm. (If next step fails somehow)
cpanm --interactive Task::Catmandu # install Catmandu
catmandu -h
````

Installing Catmandu via cpanm took me quite some time though because of fetch/config/build of all the dependencies.

I suggest to add this to the installation instructions for OSX users.

**Comment by phochste** [comment]
Thanks! Added to the Wiki
