### ISSUE TITLE
Rethink Validators

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#209]
The basic design of [Validators](https://github.com/LibreCat/Catmandu/wiki/Validators) seem to be improvable. Right now there are only two of them:
- [Catmandu::Validator::Simple](https://metacpan.org/pod/Catmandu::Validator::Simple) validates with a code reference (option `handler`)
- [Catmandu::Validator::JSONSchema](https://metacpan.org/pod/Catmandu::Validator::JSONSchema) validates with JSON Schema, given as file (`schema`).

All validators I can think of fall into this categories: either you have a piece of code in some programming language or as interface to call (e.g. an executable or a web service) or you have a schema in some schema language. We should think how to use both in a consistent way, also from the command line client and in fix language. The current version of [Catmandu::Validator](https://metacpan.org/pod/Catmandu::Validator) does not mention use in fixes and/or command line.
### Some thoughts and opinions

Validators should be usable in fix language without having to write a new fix function for each validator. For instance:

```
# reject all items not conforming to a schema
select valid(schema: "my/schema.json", validator: "JSONSchema")

# execute a script to check the author field. 
unless valid(author, schema: "check_author.script")
   ... # repair or give warning
end
```

The first call is too long, any better ideas?

Validators should be usable from command line, for instance:

```
catmandu validate JSON with JSONSchema --schema my/schema.json < input.json
catmandu convert ... --validate JSONSchema --schema my/schema.json ...
```

By the way fix scripts can be used as validator by use of `reject` and `select`, so fix scripts so we could need `Catmandu::Validator::Fix`. Fix conditions `all_match` and `any_match` are useful but schema languages make sense. For instance imagine a list if fields, each followed by their occurrence and an optional pattern:

```
name, 1
phone, 0..n, ^[0-9 -]+$
age, 0..1, ^[0-9]+$
```

Validation can also be used in multiple levels to reject some items and give warnings for others.

**Comment by nichtich** [comment]
Validators are not supported in `catmandu info` yet (workaround `catmandu info --namespace=Catmandu::Validator`). `catmandu help validate` should give some help.

**Comment by phochste** [comment]
This catmandu info was a general problem that is fixed now in the dev branch. It only showed version information about Stores,Fixes and all that but not all the rest. In the dev branch it shows informatio about the complete Catmandu namespace

**Comment by nichtich** [comment]
Validators should also have a common error class. Catmandu::Validator::Simple uses error strings while Catmandu::Validator::JSONSchema uses hashes with fields property and message. How about an error class `Catmandu::ValidationError`?

**Comment by nichtich** [comment]
@phochste I meant `catmandu info --validators` ([just implemented](https://github.com/LibreCat/Catmandu/commit/aa49e7c28fa1055d098b392b76c1f2b7f160a34d)).

See also https://github.com/LibreCat/Catmandu/wiki/Missing-modules#fixes-and-binds for more ideas about validators, for instance a fix command to validate (parts of) items.

**Comment by nics** [comment]
The valid fix is now in dev

**Comment by nichtich** [comment]
This issue can be closed with introduction of **Catmandu::Fix::validate** (in the `dev` branch) in addition to the `valid` fix.
