### ISSUE TITLE
Make JSON importer default multiline

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#210]
The most common format I use to import is JSON, so it is very annoying to always enable option multiline. The JSON importer should read real JSON as expected, instead of Line delimited JSON, as it does now. I don't mind adding a [NDJSON](http://ndjson.org/) importer (or another name, there seems to be no consensus yet) with the current default but the plain JSON importer should not throw an error when fed with anything conforming to RFC 7159. This change is backwards compatible because newline-separated JSON can still be read with multiline enabled.

**Comment by nics** [comment]
Changing the default in the corresponding exporter is not backwards compatible. But i agree, it's a better default.

**Comment by vpeil** [comment]
what about @nichtich last sentence!? a test should prove it!

**Comment by nics** [comment]
hi vitali, i just added a test for that case, will push it later today

**Comment by nics** [comment]
Changed in fa8cbfc67eda0bbc47d97b02ed57c0c9c5193028. The importer and exporter now have a line_delimited option. The changes in the importer are backwards compatible, but the changes in the exporter are NOT. You can prepare your code for 1.0 by adding line_delimited=>1 to the exporter options. This option will be ignored by current code and picked up by Catmandu::Exporter::JSON >= 1.0.
