### ISSUE TITLE
Support escape characters in CSV import options

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#213]
Instead of writing:

    catmandu convert CSV --header 1 --sep_char "?" < data.csv

where '?' is a tab-character. Write

    catmandu convert CSV --header 1 --sep_char "\t" < data.csv

**Comment by jorol** [comment]
Fixed in #215. Supports all [character escapes](http://perldoc.perl.org/perlrebackslash.html#Character-Escapes), although not all are good field seperators...
