### ISSUE TITLE
dot in XML element name impedes traversing tree

### ISSUE THREAD

**Issue by netsensei** [LibreCat/Catmandu#216]
I'm trying to import/convert an XML input which is actually XAML. One of the characteristics of XAML is the repetition of parent names in child element names separated by a dot:

Example:

```
<Production>
   <Production.creator>Firstname Lastname>/Production.creator>
   <Production.dateOfBirth>11/22/33</Production.dateOfBirth>
</Production>
```

Catmandu::XML will pull the data in and deserializes it internally into a traversable tree. The problem is that the keys in each element also contain the dot between parent/child name. When you are selecting an item in say a template toolkit template, you will run into a conflict:

This will yield an empty result as there is no separate creator element 2 levels deep:

```
[% Production.production.creator %]
``` 

My temporary solution:  regex replace the dot in the element names to an underscore with a separate command before processing the data with catmandu.

Thoughts?

**Comment by phochste** [comment]
Indeed it is problematic in Catmandu and Template toolkit to have keys which contain dots. But in this case there is an easy solution:

    catmandu convert XML --root Production to Template --template /tmp/template.tt < /tmp/data.xml

where /tmp/template.tt is like:

    [% Production.item('Production.creator') %]

The  --root Production puts the generated XML in a hash called Production. The item() method in Template Toolkit is another way to read hash data.

**Comment by netsensei** [comment]
Okay. But does this also work recursively? Suppose:

```
<Production>
   <Production.creator>
      <Creator.firstname>First Name</Creator.firstname>
      <Creator.lastname>Last Name></Creator.lastname>  
   </Production.creator>
   <Production.dateOfBirth>11/22/33</Production.dateOfBirth>
</Production>
```

**Comment by phochste** [comment]
Yup.

     $ catmandu convert XML --root Production to Template --template /tmp/template.tt < /tmp/data.xml    

with template.tt as:

    [% Production.item('Production.creator').item('Creator.firstname') %]

gives

First Name

A bit more verbose due to the dots. But , if you can get hold of a nice name of the root element, all the rest follows.
