### ISSUE TITLE
option "--transaction" for Catmandu::Cmd::import

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu#217]
The package Catmandu::Cmd::import should have an option "--transaction".
This is what it should do:
- check if the destination store supports transaction, i.e. supports Catmandu::Transactional
- wrap the import in a transaction block

Maybe in combination with an option like "--delete-all"?

**Comment by nics** [comment]
The import and copy commands got a transaction option in fd5aa4d9fdebb2a285a1a3309308bd8b980851c3
