### ISSUE TITLE
Better nameing conventions for Catmandu projects

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#219]
Create an better logic in naming Catmandu-Store packages. In some case you need to install 'Catmandu::Store::<Project>' in some cases 'Catmandu::<Project>'. E.g

```
Catmandu::Solr
Catmandu::DBI
Catmandu::FedoraCommons

vs

Catmandu::Store::MongoDB
Catmandu::Store::ElasticSearch
```

**Comment by vpeil** [comment]
I would prefer `Catmandu::XXX`. Such a package can then contain other stuff related to the store, e.g. some specific fixes or mappings...

**Comment by nichtich** [comment]
Question has been answered.
