### ISSUE TITLE
Catmandu::Fix::import

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/Catmandu#220]
The fix Catmandu::Fix::import uses data located at "file", and imports it into the specified key.

But the Catmandu::Importer can also load from a string.
In that case it should load data from the string located at the
specified key.

So we can do this

```
import('fXML','MARC','type' => 'XML')
```

which is equivalent to

```
my $str = $record->{fXML};
my $importer = Catmandu::Importer::MARC->new(
  type => "XML",
  file => \$str
);
$record->{fXML} = $importer->first();
```

By the way, when the argument "file" in the fix "import" is not given, the fix "hangs"
because it tries to read from the STDIN. Maybe it should try to read from the string
by default when no "file" is given?

**Comment by nics** [comment]
implemented is import_from_string in Catmandu 1.04
