### ISSUE TITLE
typo in POD for Catmandu::Iterable

### ISSUE THREAD

**Issue by jonassmedegaard** [LibreCat/Catmandu#224]
Catmandu::Iterable contains the non-word "containes" - should be "contains" (without an "e").

Credit goes to Vasudev Kamath <kamathvasudev@gmail.com> for spotting (and patching) this in the Debian package.

**Comment by nics** [comment]
thanks! corrected in commit fe5ce916c6d37d674e79c57a952ec7cf1516b2aa
