### ISSUE TITLE
missing POD NAME section in Catmandu::Logger

### ISSUE THREAD

**Issue by jonassmedegaard** [LibreCat/Catmandu#225]
Catmandu::Logger contains POD but lacks a NAME section.

Credit goes to Vasudev Kamath <kamathvasudev@gmail.com> for spotting (and patching) this for the Debian packaging.

**Comment by nics** [comment]
yes it does:

  =pod
  =head1 NAME
  Catmandu::Logger - A role for classes that need logging capabilities
