### ISSUE TITLE
Don't duplicate argument parsing in Catmandu::Cmd::{config,info}

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#235]
Command line parsing code is duplicated in Catmandu::Cmd::config and Catmandu::Cmd::info. The latter does not work as expected:

```
catmandu info to YAML --fix 'retain(name)'
```

does not apply the fix.

**Comment by nics** [comment]
config is ok as of 1.0306

**Comment by nics** [comment]
info is also ok since 1.04
