### ISSUE TITLE
Build a Catmandu integration test platform

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#239]
Make a way to be able to test a dev version of Catmandu against all other Catmandu projects to see if there are some breaking changes.

See the work of Rene Becker http://www.perl-services.de/ on Mojolicious pluhins

**Comment by jorol** [comment]
Slides of his Talk are available here https://speakerdeck.com/reneeb_perl/der-weg-zur-ersten-millionen-dot-dot-dot

**Comment by phochste** [comment]
See: https://github.com/LibreCat/Catmandu-Tests
