### ISSUE TITLE
Catmandu::Cmd::run does not explain how to export data

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#240]
The given example does not produce any output:

```
#!/usr/bin/env catmandu run
do importer(Mock,size:10)
  add_field(foo,bar)
end
```

By the way, why is Catmandu::Fix::add_to_exporter not named Catmandu::Fix::export?

**Comment by phochste** [comment]
You need to add a line that says which exporter you want to use:

   #!/usr/bin/env catmandu run
   do importer(Mock,size:10)
     add_field(foo,bar)
     add_to_exporter(.,JSON)
   end

Indeed add_to_exporter is not the best name. It was choosen because 'add_to_store' already existed. It would be better indeed to call them 'export' and 'store'
