### ISSUE TITLE
Tidy codebase

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu#246]
Hi,

as discussed at the workshop I've added `Code::TidyAll` to branch `tidy` in my Catmandu [repository](https://github.com/jorol/Catmandu/commit/b7951c591cfe56eef638868a9423f7129c370ae6):

* `.perltidyrc` contains the formatting options (see [documention](https://metacpan.org/pod/distribution/Perl-Tidy/bin/perltidy)). 
* `.tidyall` defines which files should be tidied. 
* `xt/release/perltidy.t` is only executed for releases.
* add `.tidyall.d/` to `.gitignore`
* add dependencies to `.travis.yaml` and `.cpanfile`

Before a release run `$ tidyall -a` in the project directory and commit the changes. You can see the result [here](https://github.com/jorol/Catmandu/commit/c1e8f73127a6a3c6f607cd58c4c8bfad53187a34). As @nics wished I've set it to a "tight" formatting, violating some "Perl Best Practices". It would be nice to get some feedback on the formatting so we can adjust the options to a common profile.

Johann

**Comment by nichtich** [comment]
Looks fine; thanks.  I'm ok with any coding rules.

On 25. April 2016 09:15:22 MESZ, Johann Rolschewski <notifications@github.com> wrote:
>Hi,
>
>as discussed at the workshop I've added `Code::TidyAll` to branch
>`tidy` in my Catmandu
>[repository](https://github.com/jorol/Catmandu/commit/b7951c591cfe56eef638868a9423f7129c370ae6):
>
>* `.perltidyrc` contains the formatting options (see
>[documention](https://metacpan.org/pod/distribution/Perl-Tidy/bin/perltidy)).
>
>* `.tidyall` defines which files should be tidied. 
>* `xt/release/perltidy.t` is only executed for releases.
>* add `.tidyall.d/` to `.gitignore`
>* add dependencies to `.travis.yaml` and `.cpanfile`
>
>Before a release run `$ tidyall -a` in the project directory and commit
>the changes. You can see the result
>[here](https://github.com/jorol/Catmandu/commit/c1e8f73127a6a3c6f607cd58c4c8bfad53187a34).
>As @nics wished I've set it to a "tight" formatting, violating some
>"Perl Best Practices". It would be nice to get some feedback on the
>formatting so we can adjust the options to a common profile.
>
>Johann
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LibreCat/Catmandu/issues/246

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by nics** [comment]
Great! Formatting looks fine to me. Just merged into dev.
