### ISSUE TITLE
Avoid deprecated File::Slupr::Tiny

### ISSUE THREAD

**Issue by jonassmedegaard** [LibreCat/Catmandu#257]
Hi,

File::Slurp::Tiny has been deprecated.

Please consider instead use its direct replacement File::Slurper, or (my favorite) Path::Tiny which is somewhat a superset likely to be useful also elsewhere in the code.

 - Jonas

**Comment by jorol** [comment]
I second the use of Path::Tiny, great module for path and file handling!
