### ISSUE TITLE
Add official short alias of catmandu command

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#264]
I was suprised that [`cm` is not used](https://packages.debian.org/search?searchon=contents&keywords=cm&mode=path&suite=stable&arch=any) by any popular command line tool yet. Sure this can be added for instance to `.bashrc`

```
# catmandu is too long to type
alias cm=catmandu
```

but an official alias would be easier for users. By the way a similar two letter command is [`jq`](https://stedolan.github.io/jq/)

**Comment by pietsch** [comment]
I'm afraid `cm` is already taken by `config-manager`. This is what I see on Debian testing:
````sh
$ cm
The program 'cm' is currently not installed.  To run 'cm' please ask your administrator to install the package 'config-manager'
````

**Comment by pietsch** [comment]
Interestingly, `cmd` is not taken on Linux, but of course this is the command interpreter for Windows. So how about `cmdu`? If something shorter is desired, how about `c` oder `ca`?

**Comment by nichtich** [comment]
`c` is too short. `cmdu` is better than `catmandu` but two or three
letters would be better any arguments against `cmu`?

**Comment by pietsch** [comment]
`cmu` is a well-known university not involved in this project. Why not `ca`?

**Comment by vpeil** [comment]
what about `cdu`? (AFAIK no linux command)

**Comment by vpeil** [comment]
Oh, I just notice that it has some familiarity with a german political party :dizzy_face:

**Comment by vpeil** [comment]
So, `cmu` seems to be more convincing

**Comment by phochste** [comment]
@vpeil haha

**Comment by nics** [comment]
i like ca

**Comment by vpeil** [comment]
so `ca`? How do we implement this? There's seems no appropriate module on cpan for that. Should we cheat be setting a symlink  to bin/catmandu?

**Comment by nics** [comment]
`bin/catmandu` is only 5 lines of code, we could just duplicate this.

**Comment by vpeil** [comment]
see pull request #275

**Comment by nics** [comment]
I'm going to close this issue. It's too easy to step on someone else's toes, and it's trivial to make an alias in your shell.
