### ISSUE TITLE
How to delete a field in a catmandu.yml configuration by overwriting?

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#266]
Given I have a catmandu.aaa.yml file with content:

    ---
    foo:
       bar:
          test: 1234
          best: 5678
          rest: xyz

What is the procedure, by adding a second configuration file, to delete the value foo.bar.best?

If I create a  `catmandu.bbb.yml `:

    ---
    foo:
       bar:
          test: 1234
          rest: xyz

then

    $ catmandu config

still shows the foo.bar.best value.

If I create a `catmandu.bbb.yml `:

    ---
    foo:
       bar: {}

them the `$ catmandu config` still shows all foo.bar.* fields.

This `catmandu.bbb.yml` will create a foo.bar.best with a `null` value..but the field still exists:

    ---
    foo:
       bar:
          best: null

Some hints form Config::Onion @dsheroh ?

**Comment by dsheroh** [comment]
Sorry for the slow reply.  I'm just back from a long vacation in the US and haven't been monitoring this email account.

Internally, the actual merging of configuration layers is done by Hash::Merge:Simple, which doesn't seem to provide for deleting items from hashes.  Please add this as a Config::Onion bug on github and I'll add support for it (probably by setting the value to " DELETE " (with leading and trailing spaces) or similar), hopefully within the next week or so.

**Comment by phochste** [comment]
With the new Config::Onion this should be solved
