### ISSUE TITLE
Fix: possible to merge hashrefs?

### ISSUE THREAD

**Issue by netsensei** [LibreCat/Catmandu#267]
Hi.

I'm creating a fix which creates an XML element. These have two types of data: a value and a set of attributes. To keep things simple, the value is a literal string.

Now my fix looks something like this:

````
add_field('value', 'myvalue')
add_field('attributes', '')
set_array('attributes', type: local, lang: en)
my_xml_element_add(xml.dom.path.node.leaf, value, attributes)
````

The idea is that one can easily add XML elements through fixes with a value and (optional) attributes set. Now the issue is my fix code. When implementing emit_create_path, I need to pass an anonymous subroutine. Currently it looks like this:

````
$perl .= $fixer->emit_create_path(
	$fixer->var,
	$new_path,
	sub {
		my $path_var = shift;
		return "${path_var} = {"
			."'_' => ${h},"
			."'lang' => '".$self->lang."',"
			."'type' => '".$self->type."'"
			."};";
	}
````

Now those attributes 'lang' and 'type' are hard coded in the fix itself. The problem is that the XML schema I'm implementing is quite complex.  Hard coded properties forces me to implement a fix either for each and every element or complextype.  So, I'm looking for a way to merge the "attributes" on runtime seamlessly in the ${path_var} hashref.  Currently, I have this:

````
$perl .= $fixer->emit_create_path(
	$fixer->var,
	$lido_path,
	sub {
		my $path_var = shift;
		return "${path_var} = {"
			."'_' => ${h}"
			."};
	}
);
````

So, that takes care of the value (which is stored in ${h}). Now I also need a way to add or merge the "attributes" (which I store in a ${e} variable) to the ${path_var} variable. The big issue is that I can't seem to be able to merge both hashrefs ($path_var and $e) into $path_var.

 So far, closest I came is with this code:

````
$perl .= $fixer->emit_create_path(
	$fixer->var,
	$lido_path,
	sub {
		my $path_var = shift;
		return "${path_var} = {"
			."'_' => ${h}"
			."};
			**while (my (${k}, ${v}) = each (%{${e}})) {
				${path_var}{${k}} = ${e}->{${k}};
			};";**
	}
);
`````
So, what I'm trying to do here is to read out the values of the ${e} variable (attributes) and merge them into the ${path_var} hash through a while loop. (I know, not the best way, but it's the most verbose way for debugging purposes)

I can also do things like `${path_var} = { %${path_var}, %${e} }` but that seems to throw up all kinds of errors.

So instead, I wanted to take a step back. I wondered: is it possible to "merge" two hashrefs in the anonymous function passed to `emit_create_path`?

PS: ${h} and ${e} are just variables created with $fixer->generate_var. They are filled with data through the `walk` routine before executing `emit_create_path` which generates the actual Perl code.  I understand that the subroutine is just a way of adding data to the subroutine.

**Comment by jorol** [comment]
Hi,

did you tried using [Catmandu::XML](https://metacpan.org/pod/Catmandu::XML)? I think you can create elements with attributes using the [XML::Struct](https://metacpan.org/pod/XML::Struct) data structure.

**Comment by nics** [comment]
Hi Matthias,

it’s hard to give you a good answer without seeing the errors, but
you could use Hash::Merge::Simple to merge the two hashes.

use Hash::Merge::Simple ();
$perl .= $fixer->emit_create_path(
    $fixer->var,
    $lido_path,
    sub {
        my $path_var = shift;
	“${path_var} = {'_' => ${h}};” .
        "if (is_hash_ref(${e})) {" .
            "${path_var} = Hash::Merge::Simple::merge(${path_var}, ${e});" .
        "}";
    }
);

Regards,
Nicolas

**Comment by netsensei** [comment]
@jorol FWIW: This code extends [Catmandu::Lido](https://github.com/LibreCat/Catmandu-LIDO) and [Lido::XML](https://metacpan.org/pod/Lido::XML). Both of which depend on LibXML::xml.

@nicolasfranck 

Yes! Thanks! That's what I was looking for. I turned your code into this:

````
$perl .= $fixer->emit_create_path(
	$fixer->var,
	$lido_path,
	sub {
		my $path_var = shift;
		return "if (is_hash_ref(${e})) {"
          . "${path_var} = Hash::Merge::Simple::merge({'_' => ${h}}, ${e});"
			."};";
	}
);
````

This works for me as intended: I get an XML element with a value and attributes.

Notice how I directly assign the result of the merge to ${path_var}. I couldn't get it to work trying to merge the value hash as an initialised ${path_var} variable.  I spent the better part of the last two hours struggling with this error when I tried to do a `print ${path_var}` directly after assigning the value hash to ${path_var}

````
Oops! One of your fixes threw an error...
Source: Catmandu::Fix::lido_map=HASH(0x7f99a93de748)
Error: Use of uninitialized value in print at (eval 960) line 1, <DATA> line 1.
````

I guess you can't alter ${path_var} after it has been set. Which seems a bit counter-intuitive since it's all just Perl code that gets generated.

Thanks again!

Matthias
