### ISSUE TITLE
Add support to rename fields based on regex expressions

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#272]
E.g.  for any fields containing a period '.' replace this with an underscore '_'.

Maybe this already possible. But an example would be welcome

**Comment by nics** [comment]
Could you give an example?

**Comment by phochste** [comment]
For instance, when processing Adlib XML documents using Catmandu::XML it will generate a key/value pairs where the keys contain periods in the name:

    first.name => 'James'
    last.name  => 'Brown'
    address => {
         street.name => 'Funkstreet'
         street.number => '1'
    }

With a fix I want to see all the periods '.' replaced by underscore '_' in the keys.

**Comment by nics** [comment]
bb7765fc78323dd3d879ac91737d745c3f41b36c introduces a new rename fix
