### ISSUE TITLE
Catmandu info no version numbers , no fixes, too long lines

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#277]
The output of the Catmandu 'info' command isn't very practical in perlbrew installations (or carton). The version numbers of all installed packages are 'undef'. Due to the long description lines of some packages the Table output is unreadable. It is possible to request another output by using an exporter:

    $ catmandu info to TSV

but it is not possible to select which columns to see with a fix:

    $ catmandu into to TSV --fix 'retain(name)'

**Comment by nics** [comment]
version numbers are shown since 050949f88d77333880cb65c2414ad71398568c91. Exporter options added in dce37a7556d97682c6474ca47c581d33dc6f7c90.
