### ISSUE TITLE
It should be able to dynamically find out if a store does cql_query

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#282]
One can find out if a Store::Bag implements a search function

    $bag->does('Catmandu::Searchable');

But there is no way to find out if the CQL query language is supported.

**Comment by nicolasfranck** [comment]
I think it's better to split these capabilities (which are now one):

* Catmandu::Searchable that requires "search", "searcher" and "delete_by_query"
* Catmandu::Searchable::CQL, which is a subclass of Catmandu::Searchable, and that adds translate_sru_sortkeys and translate_cql_query

The around-modifier for cql could then be transported to this new package

That way Catmandu::Searchable can be used for stores that cannot support CQL without putting something like "die('not supported')" in the body of these methods ;-)

**Comment by nics** [comment]
added CQLSearchable role
