### ISSUE TITLE
Catmandu::Cmd fails with a strange error message.

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/Catmandu#286]
Hi,
since my call of Catmandu would reveal some sensitive information, I won't show the exact call, but it is using the `convert LDAP` arguments. The error is quite obscure:
Oops! Undefined subroutine &Catmandu::Cmd::is_array_ref called at /opt/local/lib/perl5/site_perl/5.24/Catmandu/Cmd.pm line 85.

Since the subroutine isn't defined I suspect a programming error, like haven't imported the module where it is defined in.

**Comment by phochste** [comment]
You are referring to the repeated arguments bug. This has been fixed in Catmandu 1.0305. Upgrade your installation accordingly

https://metacpan.org/source/NICS/Catmandu-1.0305/Changes
