### ISSUE TITLE
Syntax error when running do hashmap

### ISSUE THREAD

**Issue by minorscience** [LibreCat/Catmandu#287]
Attempting to create a quick hashmap for use by another fix. Simple example:

`catmandu convert CSV to Null --fix 'do hashmap(exporter:CSV,join:",");nothing();end' < lookup.csv`

lookup.csv is:
```
key,value
1234,"item.1"
1234,"item.2"
1234,"item.3"
```

Error returned:
```
Oops! Syntax error in your fixes...

	Expected end of input on line 1 at:
do hashmap(exporter:CSV,join:",");nothing();end
^
Source:

	do hashmap(exporter:CSV,join:",");nothing();end
```
Running 1.0305 on Mac OS.

**Comment by phochste** [comment]
The `do(..) FIX; FIX; end` is a block with one or more statements. The semicolon ';' at the end of the do isnt needed.

This should work:
```(bash)
catmandu convert CSV to Null --fix 'do hashmap(exporter:CSV,join:",") nothing(); end' < lookup.csv
```
