### ISSUE TITLE
Memory leak in inline fixes 

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#291]
Using Perl 5.10, Catmandu 1.0306.

This perl program:

    use Catmandu;
    use Catmandu::Fix::retain as => 'retain';

    my $importer = Catmandu->importer('Mock');
    $importer->each( sub {
        my $data = $_[0];
        $data = retain($data,'_id');
    });

will run until all memory is filled and crash

**Comment by phochste** [comment]
Same behavior in perl 5.22

**Comment by phochste** [comment]
The problem is that Perl modules with lazy class variables never seem to go out of scope. The `Inline` code can is in simple form something like the code below. The `Test->new` in the while loop will create new `Test` and `Test2` instances which never get destroyed (sub `DESTROY`  is never called). When one deletes the `lazy` instances from the code, then `DESTROY` gets called.

It is very costly to create Moo classes with `lazy` parts.

    package Test2;
    use Moo;
    has fixes => (is => 'ro');
    sub fix {
        my ($self, $data) = @_;
    }

    package Test;
    use Moo;
    has fixer => (is => 'lazy');

    sub _build_fixer {
        my ($self) = @_;
        Test2->new(fixes => [$self]);
    }

    sub fix {
        my $self = shift;
        my $fixer = $self->fixer;
    }

    sub DESTROY {
        my ($self) = @_;
        warn "ok";
        undef $self->{fixer};
    }

    package main;

    while(1) {
        my $x = Test->new;
        $x->fix();
    }

**Comment by phochste** [comment]
Proposed fix solves the memory leak, but returns always the same fixer regardless of the passed arguments.

**Comment by nics** [comment]
memoized in 7cc30e78ca6605fbbb8a5791eacfa3dcdac833a6
