### ISSUE TITLE
Support logical NOT in the fix language

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#298]
I would like to write on the command line:

    $ catmandu convert JSON --fix "error('no id?') if not exists(id)" < data.json 

And make a guard accept also the term "if"

    fix() exists(bla)
    fix() if exists(bla)

means the same

**Comment by nics** [comment]
b748efd1adf5776372fdae2292dd483c4b5d9ca7 introduces simple boolean short circuiting:

  exists(bla) and fix()
  exists(bla) && fix()
  exists(bla) or fix()
  exists(bla) || fix()
