### ISSUE TITLE
Catmandu 1.04 breaks LibreCat

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/Catmandu#299]
We are using LibreCat 0.5.3 and [discovered](https://github.com/subugoe/goefis/issues/138) that breaks if we are using Catmandu 1.04 with it. We also don't use the latest version of `Catmandu::Store::Elasticsearch`, since there is still an [issue](https://github.com/LibreCat/Catmandu-Store-Elasticsearch/issues/15) left open. If this problems is caused by the combination of Catmandu 1.04 and `Catmandu::Store::Elasticsearch` 0.0505 then this dependency has to be resolved first.

**Comment by phochste** [comment]
Moved to https://github.com/LibreCat/LibreCat/issues/243
