### ISSUE TITLE
Catmandu v1.04 build failure on Windows

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu#300]
The install of Catmandu v1.04 failed on my Windows 7 (StrawberryPerl v5.18.2) machine:

```terminal
...
Files=156, Tests=1807, 625 wallclock secs ( 0.87 usr +  1.03 sys =  1.90 CPU)
Result: FAIL
Failed 13/156 test programs. 24/1807 subtests failed.
-> FAIL Installing Catmandu failed.
```

See also <http://fast-matrix.cpantesters.org/?dist=Catmandu%201.04>.

The problem seems to be a missing module:

```terminal
t/Catmandu-Buffer.t ...................... ok
Can't locate I18N/Langinfo.pm in @INC (you may need to install the I18N::Langinfo module) 
``` 

It seems that this module is not available for Windows (see <https://lists.gt.net/perl/porters/318168> and <https://github.com/perl-pod/Pod-Spell/issues/18>).

As I use Catmandu on Windows quite often, it would be nice if we could support it further.

**Comment by nics** [comment]
builds starting failing since 1.0304: http://fast-matrix.cpantesters.org/?dist=Catmandu%201.0304

**Comment by nics** [comment]
34dcf576e47b9c94b7b42caa38063826ef337961 should fix this

**Comment by jorol** [comment]
Works on my machine;-) Thanks.
