### ISSUE TITLE
Installation fails on macOS 10.12

### ISSUE THREAD

**Issue by minorscience** [LibreCat/Catmandu#302]
Following instructions here:
https://github.com/LibreCat/Catmandu/wiki/Installation

Installation fails at:

<pre>
--> Working on MARC::File::MARCMaker
Fetching http://www.cpan.org/authors/id/E/EI/EIJABB/MARC-File-MARCMaker-0.05.tar.gz ... OK
Configuring MARC-File-MARCMaker-0.05 ... OK
Building and testing MARC-File-MARCMaker-0.05 ... OK
Successfully installed MARC-File-MARCMaker-0.05
! Installing the dependencies failed: Module 'Catmandu' is not installed, Module 'MARC::Spec' is not installed, Installed version (0.98) of Test::Simple is not in range '1.001003', Installed version (0.98) of Test::More is not in range '1.001003'
! Bailing out the installation for Catmandu-MARC-1.09.
79 distributions installed
</pre>

**Comment by phochste** [comment]
Did you try the OSX install instructions?  https://github.com/LibreCat/Catmandu/wiki/Installation#osx

If not can you give some information on the Perl version used and availability of libxml++ libxml2 xml2 libxsl on the system?

**Comment by minorscience** [comment]
Yes, followed the instructions through:

cpanm Catmandu Catmandu::MARC

I am away from my desk but will follow up this evening.

**Comment by minorscience** [comment]
Whoops! Sorry, brand new machine and I simply forgot to install XCode first. All is well.

**Comment by phochste** [comment]
I'll add it to our wiki ;)
