### ISSUE TITLE
Catmandu::Util::data_at

### ISSUE THREAD

**Issue by cKlee** [LibreCat/Catmandu#306]
I like to document this function (and other data functions) see https://github.com/cKlee/Catmandu/blob/cKlee-patch-1/lib/Catmandu/Util.pm#L758-L813.

The problem with the data_at function is, I don't really understand it. For beginning, the option `key` seems unnecessary to me:

```perl
data_at('my.very.deep', $data, create => 1, key => 'path');
# same as?
data_at('my.very.deep.path', $data, create => 1);
```
If option `key` ist not set, the last segment of `$path` will be used as `key`. 
Both calls creating `my.very.deep = { }`

Further the value of option `key` is somehow arbitrary, because this value will not be used as a key in the created path. It's rather an indicator for data_at to decide what to create (an array or a hash). This way any value of `key` if it's numeric or starts with `$` will trigger an array and every other value will trigger a hash. 

```perl
$arr_ref = data_at('my.very.deep', $data, create => 1, key => '$');
$arr_ref = data_at('my.very.deep', $data, create => 1, key => '1');
$hash_ref = data_at('my.very.deep', $data, create => 1, key => 'a_name_does_not_matter');
```

So the name (`key`) of this option seems misleading. I'd rather expect something like `type` with values like array and hash.

Another thing I don't really understand:

```perl
# creating a path with an empty array
$arr_ref = data_at('my.very.deep', $data, create => 1, key => '$'); # my.very.deep = [ ]

# fill data
set_data($arr_ref, '0', 'foo'); # my.very.deep = [ 'foo' ]
```

So far so good. Now I want to append an array as the second element. This should look like `my.very.deep = [ 'foo', [ 'bar' ] ]`. I could produce a reference to the already existing array and fill in an array . Like

```perl
# refer to array
$arr_ref = data_at('my.very.deep', $data);
set_data($arr_ref, '$append', ['bar']);
``` 

But things become complicated when I try to create a nested data structure on advance:

 ```perl
# append an empty array as second element
 $arr_ref = data_at('my.very.deep', $data,  create => 1, key => '$append');
```

No! That was not right. Result is `my.very.deep =  [  'foo'  ]`

Have another try ...

 ```perl
$arr_ref = data_at('my.very.deep.$append', $data,  create => 1, key => '$');
``` 

Ups! Result is `my.very.deep =  [  'foo', undef, [  ]  ]`

Ok! Another one...

 ```perl
$arr_ref = data_at('my.very.deep', $data,  create => 1, key => 1);
# same as
$arr_ref = data_at('my.very.deep.1', $data,  create => 1);
``` 

Hm? I expected this to work. Result still is `my.very.deep =  [  'foo' ]`

Just playing around ...

 ```perl
$arr_ref = data_at('my.very.deep.1', $data,  create => 1, key => 1);
``` 

Eureka! Result now is `my.very.deep =  [  'foo', [ ] ]`

All right! Let's fill it ...

 ```perl
set_data($arr_ref, '1', 'bar');
``` 

Argh! What happened? Result now is `my.very.deep =  [  'foo', [ undef, 'bar' ] ]`

Really? I'm not following you here.

But what about ...

 ```perl
set_data($arr_ref, '$append', 'bar');
``` 

Yeah! That's it. Result is now  `my.very.deep =  [  'foo', [ 'bar' ] ]`

Maybe documenting the function isn't a good idea? What do you think?

**Comment by nics** [comment]
Hi Carsten, thanks for the effort but this is older code that duplicates (and is subtly different from) what happens in Fix.pm. I would delay trying to document it, since it's up for replacement by a function that uses, or behaves the same as, Fix.pm.

**Comment by cKlee** [comment]
Yes I know! I wish there is another way than using the emit* functions. I really think they make fix development very complicated. I would rather use closures, but missing the walk_path, create, set, delete ... functionalities for that.
