### ISSUE TITLE
Add Catmandu::Store touch command

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#309]
Add a command line tool to update a 'date' field for every record in a Store.

E.g.

   $ catmandu touch <Store> --field <field>

This command needs to be used for example when the serialisation format changes in OAI frontends. See also: https://github.com/LibreCat/Dancer-Plugin-Catmandu-OAI/issues/12

**Comment by nicolasfranck** [comment]
When the bag has the plugin "Datestamps", this easily be done by resaving the records.

Advantages:
* field "date_updated" (or whatever you configured) is updated automatically, without having to know how this is stored in the backend store

Disadvantages:
* It is slow:
   * write the ids to a file
   * read this file line by line
   * fetch record
   * save record

**Comment by nics** [comment]
Mostly implemented in the feature_touch branch

**Comment by nics** [comment]
a2d5ecaae497f6e5eb5070fff06dcd4879b8598d adds a touch command and bag touch method
