### ISSUE TITLE
Installation OSX: catmandu command not found

### ISSUE THREAD

**Issue by nvanderperren** [LibreCat/Catmandu#311]
Hi, I installed Catmandu. Followed the steps of the documentation. 
When I want to use the catmandu-command, I always get: "bash-catmandu:command not found"

this is my bash_profile file:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
export "PATH=$HOME/.plenv/bin:$PATH"
eval "$(plenv init -)"
.bash_profile

**Comment by phochste** [comment]
When you first install plenv you need to restart your bash script:

```
 $ exec $SHELL -l
```

When install new  Perl modules with `plenv` you need to `plenv rehash` to add binaries to your path

```
$ plenv global 5.20.2  # in case you installed perl 5.20.2
$ plenv install-cpanm
$ cpanm Catmandu
$ plenv rehash
```

**Comment by nvanderperren** [comment]
I tried that but it's not working. 

In the documentation Homebrew is used to install cpanm. I know uninstalled the package with Homebrew and installed it again with `plenv install-cpanm` but then it says `bash  - cpanm: command not found`. 

I just followed the documentation:

```
brew install libxml++ libxml2 xml2 libxslt
# Install plenv from https://github.com/tokuhirom/plenv
git clone https://github.com/tokuhirom/plenv.git ~/.plenv
echo 'export PATH="$HOME/.plenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(plenv init -)"' >> ~/.bash_profile
exec $SHELL -l
git clone https://github.com/tokuhirom/Perl-Build.git ~/.plenv/plugins/perl-build/
# Install a modern Perl
plenv install 5.22.0
plenv rehash

brew install cpanm
# Install catmandu
cpanm Catmandu Catmandu::MARC
plenv rehash
```

(but I've now installed docker and the docker image which works fine).

**Comment by phochste** [comment]
Ah, there is an error in the documentation. Where it says:

```bash
brew install cpanm
```

it has to be:

```
plenv install-cpanm
```
