### ISSUE TITLE
Treat quotes numerals as string literals not as integers

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#317]
```
add_field(a,"910")    # a := "910"
add_field(b,910)       # b := 910
```  

Ref: https://github.com/LibreCat/Catmandu-MARC/issues/82

**Comment by nics** [comment]
I'm afraid both are just scalar's to perl. This should be handled as late as possible in the marc package by writing an interpolated literal `$record->{tag} = "$tag"`.
