### ISSUE TITLE
Autocompletion of department: If no department is found the field loses the focus

### ISSUE THREAD

**Issue by datango** [LibreCat/Catmandu#319]
When you edit a publication and try to add a department you start typing some letters. While some departments are found you can delete chars. But if no departments are found the input field loses the focus and pressing the delete key loads the previous page in the browser ("going back").

**Comment by phochste** [comment]
@datango  This ticket is in the wrong project. The LibreCat repository issue tracker is at : https://github.com/LibreCat/LibreCat/issues

**Comment by datango** [comment]
Ups! I created a new ticket there: https://github.com/LibreCat/LibreCat/issues/299
