### ISSUE TITLE
Shouldn't Iterable->map(sub {}) support zero, one or more return values for the map expression?

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#326]
In Perl it is possible to write:

```
@double = map { ($_,$_) } @input;
```

The Iterable->map only allows zero or one return value for the map expression.

This results only in a copy of $it into $it2, not a $it2 with 2 times more entries

```
my $it2 = $it->map(sub { my $n = shift; ($n,$n) }); # doesn't work as expected
```

**Comment by nics** [comment]
implemented in e2dae5a74836fc546a369807b047fd0f06a31d0c
