### ISSUE TITLE
Converting MARCXML to anything

### ISSUE THREAD

**Issue by jasloe** [LibreCat/Catmandu#332]
Attempting to convert a MARCXML record to any format and the following error is thrown:
<pre>Use of uninitialized value in concatenation (.) or string at /Users/jasonloeffler/.plenv/versions/5.22.0/lib/perl5/site_perl/5.22.0/MARC/File/XML.pm line 399, <GEN0> chunk 2.
</pre>
Here's a simple example:
<pre>
catmandu convert MARC --type XML to MARC something.fix < sh00004901.xml > sh00004901.mrc
</pre>

Where something.fix is:
<pre>
nothing()
</pre>

I've tried both a standard LC authority record....
<pre>
https://gist.github.com/jasloe/4504352ee3ef7e6f1be0285f5be0e293
</pre>
as well as the sample MARC record provided with the MARC::XML documentation....
<pre>
http://search.cpan.org/~bbirth/MARC-XML-0.4/XML.pm
</pre>

My perl environment is here: `https://gist.github.com/jasloe/87f528fd4be3b34e61ace140a9a1c369`

and <pre>brew list</pre> shows:
<pre>
bower		glib		jpeg		libsigc++	libxml2		openssl		readline
freetype	glibmm		libffi		libtool		libxslt		pcre		unixodbc
gettext		icu4c		libpng		libxml++	node		php71		xml2
</pre>
I am able to convert to and from other MARC formats as well as JSON and CSV without issue. XML seems to be the format not performing as expected. Does Catmandu expect a particular XML schema or require some preprocessing before conversion?

**Comment by cKlee** [comment]
see https://github.com/LibreCat/Catmandu-MARC/issues/67

**Comment by phochste** [comment]
Hmm.. I see the `MARC::File::XML` parser does interesting stuff.

 It requires all records in a  '<collection>' tag . Can you test if this works? Add:

```
<marcxml:collection
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.loc.gov/MARC21/slim http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd"
  xmlns:marcxml="http://www.loc.gov/MARC21/slim">
...
</marcxml:collection>
```

around your input XML. Or, if you don't use any namespaces just add `<collection>...</collection>` around your MARC.

The catmandu command you provided in this issue needs an extra `--fix` argument:

```
catmandu convert MARC --type XML to MARC --fix something.fix < sh00004901.xml > sh00004901.mrc
```

**Comment by jorol** [comment]
This is bug of MARC::File::XML: https://github.com/perl4lib/marc-perl/pull/5. It's already fixed, but no new release yet. 

@gmcharlt Could you please release a new version? Thanks
