### ISSUE TITLE
Issues with the Data::UUID module

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#367]
The Data::UUID module is used in Catmandu in several packages. In my production system already two times all my services hang because of issues with a lock/state file that is generated by Data::UUID (dead lock?). See also https://github.com/rjbs/Data-UUID/issues/5 and https://github.com/rjbs/Data-UUID/issues/33 . 

There are other options available on CPAN to generate UUIDs.

There packages rely on Data::UUID:

- Catmandu::Bag::IdGenerator::Mock
- Catmandu::Bag::IdGenerator::UUID
- Catmandu::Fix::uuid
- Catmandu::IdGenerator::UUID
- Catmandu::Store::File::Simple
- Catmandu::Store::File::FedoraCommons
- Catmandu::Store::File::BagIt
- Catmandu::DirectoryIndex::UUID

**Comment by nics** [comment]
Will be fixed in the upcoming 1.2003
