### ISSUE TITLE
set_field omits trailing dots from a literal string with digits

### ISSUE THREAD

**Issue by netsensei** [LibreCat/Catmandu#372]
e.g.

`catmandu convert Null to YAML --fix "set_field('foo', '1234.')"` will yield:

```yaml
---
foo: 1234
...
```

These values do work correctly:

* .1234.
* d1234.
* 1234.d
* 1234d.

When converting to JSON we get this result:

`catmandu convert Null to JSON --fix "set_field('foo', '1234.')"` will yield:

```json
[{"foo":1234.0}]
```
Note how `1234.` is converted to `1234.0`

Escaping the dot doesn't work:

`catmandu convert Null to JSON --fix "set_field('foo', '1234\.')"` will yield:

```json
[{"foo":1234\\.}]
```

**Comment by nics** [comment]
fixed in 1.2009
