### ISSUE TITLE
Installation fails for Perl <5.14

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#379]
Parser::MGC since 0.17 uses Feature::Compat::Try uses Syntax::Keyword::Try uses XS::Parse::Keyword requires Perl 5.14. Solutions:

1. pin Parser::MGC to 0.16 (so we are locked with this version and I think installing Catmandu would fail if you happen to have installed a newer version of Parser::MGC)
2. Install Parser::MGC@0.16 for tests on Perl 5.10 and Perl 5.12 (see https://app.travis-ci.com/github/LibreCat/Catmandu/builds/237792510). I think fresh install of Catmandu on Perl < 5.14 will still fail unless you already have installed Parser::MGC and install with `--skip-satisifed`
3. upgrade requirement to Perl 5.14

I would welcome the third option. Perl 5.14 was released more than 10 years ago. This is old enough, also given the slow update cycles of library IT.

**Comment by vpeil** [comment]
I am voting for option 3, too.
