### ISSUE TITLE
add documentation for Catmandu::Fix::Bind::each

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu#384]
I've got feedback from Catmandu users, who are missing the fix "Catmandu::Fix::Bind::each" in our [documentation](https://librecat.org/assets/catmandu_cheat_sheet.pdf) and [cheat sheet](https://librecat.org/assets/catmandu_cheat_sheet.pdf). I know both documentations are not complete, but this fix is in Catmandu core and quite handy...

**Comment by phochste** [comment]
Fixed the documentation in the Wiki also, trying to rebuild the librecat.org webpage but I don't see the changes yet appear there.

There a pandoc command in the procedure to produce a Wiki book from our Wikipages that is deprecated. Alas I am not a pandoc expert (and didn't created this routine) described in : https://github.com/LibreCat/librecat.github.io.
Maybe @nichtich can help ? I think he created the pandoc version of the Wiki as one book?

**Comment by jorol** [comment]
@phochste Thanks!

**Comment by nichtich** [comment]
@phochste can you point me to the build script, log file etc. that involves pandoc?

**Comment by phochste** [comment]
It is part of the `git@github.com:LibreCat/Catmandu.wiki.git` repository in the `book/` directory. To bad I can't point at it via the web.

**Comment by phochste** [comment]
I got the homepage generation page scripts too work..but I still don't understand completely how it works.
