### ISSUE TITLE
Wildcards-Documentation $start, $end, $first, $last

### ISSUE THREAD

**Issue by TobiasNx** [LibreCat/Catmandu#387]
There seems to be an inconsistency in the wildcard documentation:

https://github.com/LibreCat/Catmandu/wiki/Paths#wildcards

introduces:
`$first` and `$last` as wildcards for the first and the last entry in a list

https://github.com/LibreCat/Catmandu/wiki/Fixes%20Cheat%20Sheet

states:
`$start` and `$end` as wildcards for the first and the last entry (under replace_all)
no refrence to `$first` or `$last`

https://librecat.org/assets/catmandu_cheat_sheet.pdf

also only introduces `$start` and `$end` as wildcards for the first and the last entry (under replace_all)
no refrence to `$first` or `$last`

PS:
The Catmandu Website: https://librecat.org/ links from the startpage to the PDF via the menu link "Cheat Sheet" but if you are on any other subpage of the website the menu link "Cheat Sheet" links to site build from the Github-Wiki.

**Comment by phochste** [comment]
The `$first` and `$last` are the correct wildcard. I'll update the Cheatsheets. 

There is still an issue on our website, that we can't generate any updates anymore (the pandoc scripts are broken). See also : https://github.com/LibreCat/Catmandu/issues/384

**Comment by phochste** [comment]
Updates the homepage too
