### ISSUE TITLE
`retain_field` still in documentation and tutorials

### ISSUE THREAD

**Issue by TobiasNx** [LibreCat/Catmandu#391]
If I see right `retain_field` as function is deprecated, right?
But there are still multiple references in the documentation and the tutorials:

e.g.:
https://librecatproject.wordpress.com/2014/12/08/day-6-introduction-into-catmandu/
https://librecat.org/Catmandu/#fixes
https://librecat.org/Catmandu/#convert-1
https://librecat.org/Catmandu/#cookbook
https://librecat.org/Catmandu/#importexport

**Comment by vpeil** [comment]
Thanks for this hint. I've corrected the documentation and published it to the librecat.org website.

I am not going go fix the blog post.
