### ISSUE TITLE
documentation links are broken

### ISSUE THREAD

**Issue by VladimirAlexiev** [LibreCat/Catmandu#394]
Doc links (eg in http://librecat.org/Catmandu/#import)
are rendered as anchors rather than external links (eg http://librecat.org/Catmandu/#-https://metacpan.org/pod/catmandu::store::mongodb), 
and therefore are broken.

The links use somewhat unusual markdown link location:
```
[[MongoDB | https://metacpan.org/pod/Catmandu::Store::MongoDB]]
```
Whereas the usual notation looks like this:
```
[MongoDB](https://metacpan.org/pod/Catmandu::Store::MongoDB)
```

However, I checked with the Preview of github's online editor (eg https://github.com/LibreCat/Catmandu/wiki/command-line-client/_edit)
and both of the above links work as expected.

Therefore, somethink in the process of rendering Github wiki pages as HTML, breaks these external links.

Cheers!

**Comment by vpeil** [comment]
I'd willing to correct all of these.

@phochste @nichtich who remembers how this documentation is generated?

**Comment by phochste** [comment]
The text is from the wiki in this `Catmandu` project. The website is generated using the https://github.com/LibreCat/librecat.github.io project

**Comment by vpeil** [comment]
I have updated the links in the wiki. Unfortunately, I didn't manage to update the documentation on the librecat website.
@phochste can you help, please?

**Comment by nichtich** [comment]
I've updated the homepage and slightly simplified the update process, see https://github.com/LibreCat/librecat.github.io#deployment

**Comment by vpeil** [comment]
Thanks @nichtich
