### ISSUE TITLE
Support Importing stuff from a URL

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#58]
It would be very helpfull if we could do things like

$ catmandu convert JSON --url http://somewhere.org/data.json to YAML

**Comment by nics** [comment]
I started implementing this and path support for the json importer in the dev_url_get branch

**Comment by nichtich** [comment]
The implementation adds Coro (and by this AnyEvent) as additional dependency. I cannot recommend people to use Catmandu if chances are that installation will fail. This happened just to often! I'd strongly vote to keep it as separate module to not add more dependencies.

**Comment by phochste** [comment]
Would a Coro dependency on the long run not be preferable? I finding myself doing asynchronous/parallel work only these days to keep my fixes running within a time window of a few hours. On  CentOS and Debian Coro packages are available (perl-Coro resp libcoro-perl).
Of course we should make upgrades painless, but I don't think this will break the installation.

**Comment by nichtich** [comment]
Parallel processing of items would be a preferable feature to justify Coro, but it could also be made an optional `feature`. I'd expect

    catmandu convert --parallel foo to bar

to run faster but give me result items in inpredictable order as they are ready.

**Comment by nics** [comment]
simple (blocking) importing from a url is now supported
