### ISSUE TITLE
Provide pre-installed Catmandu images

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu#59]
Maybe we can provide vagrant or something images to easily create a virtual box with Catmandu + ElasticSearch + MongoDb preinstalled.

**Comment by vpeil** [comment]
automated build enabled on docker hub:
https://registry.hub.docker.com/u/librecat/catmandu/

A new docker image is built on every push to the master branch (in our case: a new release with a new version number).

Users should do
```bash
me@laptop $ sudo docker pull librecat/catmandu
me@laptop $ sudo docker run -it librecat/catmandu
root@{docker-container-id} $ catmandu help
```

**Comment by nichtich** [comment]
Thanks! Could you please add instructions at https://github.com/LibreCat/Catmandu/wiki/Installation?

**Comment by nichtich** [comment]
I added installation instruction. When the image contains additional software such as MongoDB this should be documented too.

**Comment by nichtich** [comment]
I'd prefer two Docker images:

* librecat/catmandu - with Catmandu core only
* librecat/catmandu-all - with Task::Catmandu (all Catmandu modules)

**Comment by vpeil** [comment]
Yes, I'd prefer the same. The current docker image contains Catmandu core only.
the second as Task::Catmandu, but then the situation ist more cmplex as ElasticSearch, Solr, MongoDB would be nice to have, so maybe we should also create a third one....
