### ISSUE TITLE
Simple mapping table as fix

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#67]
Many data conversion tables consist of simple mapping tables given as spreadsheets/csv. Fields included in a mapping table are moved/renamed andy fields not notnot included are removed. How about using csv as input format for such mapping fixes?

**Comment by nics** [comment]
It would nice to enable this with a generic solution:
```
bind args(file: mapping.csv)
  move_field(arg1, arg2)
end

```
That doesn't take care of the deletions of course.

**Comment by nics** [comment]
added mapping fix (see #366)
