### ISSUE TITLE
Compare/evaluate and refer to similar tools 

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#75]
Many tools for command line data processing exist, such as [jq](http://stedolan.github.io/jq/), [App::yq](https://metacpan.org/pod/distribution/App-YAML-Filter/bin/yq) for JSON/YAML CSVkit etc. see for instance this summary:

* http://jeroenjanssens.com/2013/09/19/seven-command-line-tools-for-data-science.html

We should have a look a these kits and copy good features to Catmandu.

**Comment by vpeil** [comment]
another example:
[csvkit](https://csvkit.readthedocs.org)

**Comment by vpeil** [comment]
a list of similar tools exits: https://github.com/LibreCat/Catmandu/wiki/Related-Projects
If any features should be adopted to catmandu it should be handled in separate issues
