### ISSUE TITLE
CLI scripts

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#91]
Calling catmandu CLI can become very verbose. this can be reduced by config files but the config file does not include the full command, e.g. 'import'. One workaround is to put the call in a shell script and additional settings in a config file, but multiple files is complex. Another workaround is a Perl script that makes use of Catmandu packages, but this is very verbose. How about a way to merge CLI call and config into a YAML script that can be executed with 'catmandu run script.yml'. The script could further be used to automatically generate a Perl script as boilerplate for further development.

**Comment by phochste** [comment]
An experimental branch is available which could be used to investigate Fix scipts. See:
the fix_importer branch https://github.com/LibreCat/Catmandu/tree/fix_importer  

In this branch it is possible to write fix scripts like

    do importer(OAI,url: "http://lib.ugent.be/oai") 
      retain(_id)
      add_to_exporter(.,YAML)
    end

and run them like:

    catmandu run myfix.fix

**Comment by phochste** [comment]
Of course, having already a feature that automatically executes fixes that have a executable attributes it would make it impossible to run these fix scripts above as:

    #!/usr/bin/env catmandu run
    do importer(OAI,url: "http://lib.ugent.be/oai") 
      retain(_id)
      add_to_exporter(.,YAML)
    end

Is it really required to keep lines 49,50 and 51 in Fix.pm?

       elsif (is_string($fix) && $fix !~ /[\n()]/ and -X $fix) {
            push @$fixes, require_package('Catmandu::Fix::cmd')->new($fix);
       }

**Comment by nichtich** [comment]
See #111 for discussion.
