### ISSUE TITLE
ISBN and ISSN

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#96]
As discussed on the mailing list, one could add to the core:

* Catmandu::Fix::isbn
* Catmandu::Fix::issn

or variants such as

* Catmandu::Fix::isbn10
* Catmandu::Fix::isbn13

This may require introduction of a new dependency so one could also release it as independent module (e.g. Catmandu::Identifiers with additional identifier systems).

**Comment by vpeil** [comment]
implemented as separate distribution: https://github.com/LibreCat/Catmandu-Identifier

**Comment by nichtich** [comment]
thanks for putting this into a separate distribution!
