### ISSUE TITLE
let importers read from multiple files

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu#99]
Given a directory of files (e.g. XML, CSV, XSL) how can one conveniently import their content with Catmandu? Right now we can

a) concat all these files (not possible for most formats)
b) call catmandu for each file (not convenient)

I suppose that most importers are not designed to be called on multiple input files (option `file` or `fh`), so Catmandu would need to create a new importer for each file. Something like this would be nice:

    ls *.csv | catmandu --files-from - convert CSV to YAML

    my $importer = Catmandu->importer(
        'CSV', 'files-from' => sub { ... } # some method to return IO handles or filenames
    );
    $importer->each( ... );

**Comment by nics** [comment]
the dev_multi_importer branch has a new MultiImporter that can help facilitate this. See t/Catmandu-MultiImporter.t for usage.

**Comment by nics** [comment]
there is now an Importer::Multi
